name:                hs-multihash
version:             0.2.1
github:              'MatrixAI/hs-multihash'
license:             BSD3
author:              ['Luke Hoersten', 'Quoc-An Ho', 'CMCDragonkai']
maintainer:          'roger.qiu@matrix.ai'
copyright:           ['2015 Luke Hoersten', '(c) Matrix AI 2017']
category:            Data
synopsis:            Multihash library and CLI executable

extra-source-files:
- README.md
- package.yaml

description:         Multihash is a protocol for encoding the hash algorithm and digest length at the start of the digest. More information available at the official <https://github.com/jbenet/multihash/multihash>.

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Data.Multihash.Base
    - Data.Multihash.Digest
    - System.IO.Streams.Crypto
  dependencies:
    - attoparsec
    - base58-bytestring
    - base64-bytestring
    - bytestring
    - cryptonite
    - hex
    - io-streams
    - memory

executables:
  multihash-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - hs-multihash
      - bytestring
      - io-streams
      - optparse-applicative
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -funbox-strict-fields
      - -fdicts-cheap
      - -O2
